### ISSUE TITLE
En715 Jetson xaiver Nx Yolov7.trt Not detect

### ISSUE THREAD

**Issue by sergenerbay** [Linaom1214/TensorRT-For-YOLO-Series#106]
I'm trying to convert and detect the same weight on my own computer and Jetson, it works fine on my own computer, but
When I experiment with Jetson, the conversions are successful but not pattern detection.
My own computer feature
Tensorrt 8.6.1
Cuda 12.2
Jetson Xaiver Nx feature
Jetpack 4.6
Tensorrt 8.0.1.6
Cuda 10.2

how can i solve this problem

**Comment by PrashantDixit0** [comment]
Any Specific Error which you are getting?

**Comment by Linaom1214** [comment]
when export the onnx make sure use FP32 precision. ---- Replied Message ----FromPrasant ***@***.***>Date09/27/2023 03:25 ***@***.***> ***@***.***>SubjectRe: [Linaom1214/TensorRT-For-YOLO-Series] En715 Jetson xaiver Nx Yolov7.trt Not detect (Issue #106)
Any Specific Error which you are getting?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Linaom1214/TensorRT-For-YOLO-Series/issues/106#issuecomment-1736158945",
"url": "https://github.com/Linaom1214/TensorRT-For-YOLO-Series/issues/106#issuecomment-1736158945",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
