### ISSUE TITLE
c++ endtoend 关于预测的置信度绘制

### ISSUE THREAD

**Issue by phhh-xh** [Linaom1214/TensorRT-For-YOLO-Series#109]
你好，感谢大佬的工作，这里想问下c++的endtoend的预测后的图片，没有绘制出每个类别的概率，这个怎么添加啊
用的是自定义的数据集
![1](https://github.com/Linaom1214/TensorRT-For-YOLO-Series/assets/127705113/d76edbee-d84d-490a-bc53-2a3f9b0e1e85)

**Comment by Linaom1214** [comment]
问题解决了吗？ ---- 回复的原邮件 ***@***.***>发送日期2023年10月19日 17:29 ***@***.***> ***@***.***>主题[Linaom1214/TensorRT-For-YOLO-Series] c++ endtoend 关于预测的置信度绘制 (Issue #109)
你好，感谢大佬的工作，这里想问下c++的endtoend的预测后的图片，没有绘制出每个类别的概率，这个怎么添加啊
用的是自定义的数据集


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Linaom1214/TensorRT-For-YOLO-Series/issues/109",
"url": "https://github.com/Linaom1214/TensorRT-For-YOLO-Series/issues/109",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by phhh-xh** [comment]
没有，是没有这个置信度的变量属性吗，需要自己添加？

**Comment by Linaom1214** [comment]
> 没有，是没有这个置信度的变量属性吗，需要自己添加？

有这个属性，添加一个score就可以
https://github.com/Linaom1214/TensorRT-For-YOLO-Series/blob/4fe770cb26c659df60ece6d50f3723cdb04492fc/cpp/end2end/main.cpp#L285C1-L315C4

**Comment by phhh-xh** [comment]
好的 感谢
