### ISSUE TITLE
Getting an issue with int8 precesion inference 

### ISSUE THREAD

**Issue by PavanAchari** [Linaom1214/TensorRT-For-YOLO-Series#49]
Ref : - https://github.com/Linaom1214/TensorRT-For-YOLO-Series/issues/45#event-7334691243

as you said earlier I have made changes at return like(return image / 255, scale )
but still, I did not get detections 
Can you please suggest what needs to be done 

Thanks & Regards,
Pavan

**Comment by Linaom1214** [comment]
> Ref : - [#45 (comment)](https://github.com/Linaom1214/TensorRT-For-YOLO-Series/issues/45#event-7334691243)
> 
> as you said earlier I have made changes at return like(return image / 255, scale ) but still, I did not get detections Can you please suggest what needs to be done
> 
> Thanks & Regards, Pavan

I used multiple models, after doing the above modification, the int8 model can detect the target. 
Can you provide more detailed information? v7 or v6 ? and how many images were used for calibration

**Comment by PavanAchari** [comment]
I have used the training images folder for the calibration and there were above 10k images in the folder 
Thanks & Regards,
Pavan

**Comment by Linaom1214** [comment]
yolox？---- Replied Message ***@***.***>Date09/10/2022 17:58 ***@***.***> ***@***.******@***.***>SubjectRe: [Linaom1214/TensorRT-For-YOLO-Series] Getting an issue with int8 precesion inference (Issue #49)
I have used the training images folder for the calibration and there were above 10k images in the folder
Thanks & Regards,
Pavan

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Linaom1214/TensorRT-For-YOLO-Series/issues/49#issuecomment-1242689937",
"url": "https://github.com/Linaom1214/TensorRT-For-YOLO-Series/issues/49#issuecomment-1242689937",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Linaom1214** [comment]
> I have used the training images folder for the calibration and there were above 10k images in the folder Thanks & Regards, Pavan

give me more details for your model.
