### ISSUE TITLE
能不能调整batch？

### ISSUE THREAD

**Issue by Swayzzu** [Linaom1214/TensorRT-For-YOLO-Series#60]
请问一个batch能不能设为2或4，一次推理多张图

**Comment by Linaom1214** [comment]
目前可以支持多batch 但是不支持 动态batch  所以一直没有更新 正在寻求解决方案---- 回复的原邮件 ***@***.***>发送日期2022年09月28日 19:07 ***@***.***> ***@***.***>主题[Linaom1214/TensorRT-For-YOLO-Series] 能不能调整batch？ (Issue #60)

请问一个batch能不能设为2或4，一次推理多张图



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/Linaom1214/TensorRT-For-YOLO-Series/issues/60",

"url": "https://github.com/Linaom1214/TensorRT-For-YOLO-Series/issues/60",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Swayzzu** [comment]
好的谢谢！

**Comment by nicken** [comment]
你好 请问如何设置呢？
